#!/bin/bash

set -e

echo "🚀 Starting production deployment..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if .env.prod exists
if [ ! -f .env.prod ]; then
    echo -e "${RED}❌ .env.prod file not found!${NC}"
    echo -e "${YELLOW}📋 Please copy .env.prod.template to .env.prod and configure it:${NC}"
    echo "   cp .env.prod.template .env.prod"
    echo "   # Edit .env.prod with your domain and email"
    exit 1
fi

# Source environment variables
source .env.prod

# Validate required environment variables
if [ -z "$DOMAIN" ] || [ -z "$ACME_EMAIL" ]; then
    echo -e "${RED}❌ Missing required environment variables!${NC}"
    echo -e "${YELLOW}📋 Please set DOMAIN and ACME_EMAIL in .env.prod${NC}"
    exit 1
fi

# Set default Traefik credentials if not provided
TRAEFIK_AUTH_USER=${TRAEFIK_AUTH_USER:-admin}
TRAEFIK_AUTH_PASSWORD=${TRAEFIK_AUTH_PASSWORD:-secure123}

# Generate Traefik authentication hash
echo -e "${YELLOW}🔐 Generating Traefik authentication hash...${NC}"
if command -v htpasswd >/dev/null 2>&1; then
    echo -e "${GREEN}   Using system htpasswd...${NC}"
    TRAEFIK_AUTH_HASH=$(htpasswd -nb "$TRAEFIK_AUTH_USER" "$TRAEFIK_AUTH_PASSWORD")
else
    echo -e "${GREEN}   Using Docker htpasswd...${NC}"
    TRAEFIK_AUTH_HASH=$(docker run --rm httpd:2.4-alpine htpasswd -nb "$TRAEFIK_AUTH_USER" "$TRAEFIK_AUTH_PASSWORD")
fi

# Escape for docker-compose (double the $ signs)
TRAEFIK_AUTH_HASH_ESCAPED=$(echo "$TRAEFIK_AUTH_HASH" | sed 's/\$/\\$/g')

echo -e "${GREEN}✅ Environment configuration validated${NC}"
echo -e "${YELLOW}🌐 Domain: $DOMAIN${NC}"
echo -e "${YELLOW}📧 Email: $ACME_EMAIL${NC}"
echo -e "${YELLOW}👤 Traefik User: $TRAEFIK_AUTH_USER${NC}"

# Create letsencrypt directory if it doesn't exist
mkdir -p letsencrypt
chmod 600 letsencrypt 2>/dev/null || true

# Stop existing containers if running
echo -e "${YELLOW}🛑 Stopping existing containers...${NC}"
docker-compose -f docker-compose.prod.yml down 2>/dev/null || true

# Create temporary env file with generated hash
echo -e "${YELLOW}🔧 Preparing configuration...${NC}"
TEMP_ENV_FILE=".env.prod.tmp"
cp .env.prod "$TEMP_ENV_FILE"
echo "TRAEFIK_AUTH_HASH_ESCAPED=$TRAEFIK_AUTH_HASH_ESCAPED" >> "$TEMP_ENV_FILE"

# Build and start services
echo -e "${YELLOW}🔨 Building and starting services...${NC}"
docker-compose -f docker-compose.prod.yml --env-file "$TEMP_ENV_FILE" up -d --build

# Wait for services to be ready
echo -e "${YELLOW}⏳ Waiting for services to be ready...${NC}"
sleep 10

# Clean up temporary files
rm -f "$TEMP_ENV_FILE"

# Check if services are running
if docker-compose -f docker-compose.prod.yml ps | grep -q "Up"; then
    echo -e "${GREEN}🎉 Deployment successful!${NC}"
    echo ""
    echo -e "${GREEN}🌍 Your portfolio is now available at:${NC}"
    echo -e "${GREEN}   https://$DOMAIN${NC}"
    echo ""
    echo -e "${YELLOW}📊 Traefik dashboard (optional):${NC}"
    echo -e "${YELLOW}   https://traefik.$DOMAIN${NC}"
    echo -e "${YELLOW}   Username: $TRAEFIK_AUTH_USER${NC}"
    echo -e "${YELLOW}   Password: $TRAEFIK_AUTH_PASSWORD${NC}"
    echo ""
    echo -e "${GREEN}🔒 SSL certificates will be automatically generated by Let's Encrypt${NC}"
    echo -e "${YELLOW}⚠️  Initial SSL generation may take 1-2 minutes${NC}"
else
    echo -e "${RED}❌ Deployment failed! Check the logs:${NC}"
    docker-compose -f docker-compose.prod.yml logs
    rm -f "$TEMP_ENV_FILE"
    exit 1
fi