version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    environment:
      - DOMAIN=localhost
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge