version: '3.8'

services:
  portfolio:
    build: .
    container_name: hamed-elfayome-portfolio
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount SSL certificates (uncomment when you have them)
      # - ./ssl:/etc/nginx/ssl:ro
      # Mount nginx logs
      - ./logs:/var/log/nginx
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`hamedelfayome.dev`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

networks:
  portfolio-network:
    driver: bridge

# Optional: Add Traefik for automatic SSL
# Uncomment if you want to use Traefik as reverse proxy
# traefik:
#   image: traefik:v2.10
#   container_name: traefik
#   restart: unless-stopped
#   ports:
#     - "80:80"
#     - "443:443"
#     - "8080:8080"  # Traefik dashboard
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock:ro
#     - ./traefik:/etc/traefik
#   networks:
#     - portfolio-network
